version: '3'
services:
  database:
    image: 'mongo:5.0.5'
    container_name: 'dsp'
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=dsp_database
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=ChangeMe
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - dsp-db:/data/db
    ports:
      - '27017-27019:27017-27019'
volumes:
  dsp-db:
